<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>flo</string>
	</array>
	<key>name</key>
	<string>FloScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.floscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>text.definition.comment.floscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)(.*)\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\s+)(-?(?:\d*\.)?\d+)\b</string>
			<key>name</key>
			<string>constant.numeric.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>support.constant.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(inactive|active|aux|slave|moot|front|mid|back|elapsed|recurred|goal|readied|started|running|stopped|aborted|next|value|all|any|me|root|actor|main)\b</string>
			<key>name</key>
			<string>entity.name.tag.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(".*?")</string>
			<key>name</key>
			<string>string.quoted.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(to|with|by|from|per|for|as|at|in|of|on|be|into|and|not|first|cum|via)\b</string>
			<key>name</key>
			<string>keyword.operator.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b|\s+)\.(\b|\s+)</string>
			<key>name</key>
			<string>keyword.operator.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if)(\s+(always|done|status|(update|change)(\s+(in))?|elapsed|recurred))?\b</string>
			<key>name</key>
			<string>keyword.operator.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;&gt;|&lt;=|&gt;=|&lt;|&gt;|\+\-)</string>
			<key>name</key>
			<string>keyword.operator.comparison.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(\s*(bid))?\s*(init|put|copy|inc|set|do|go|let|aux|need)\b</string>
			<key>name</key>
			<string>keyword.control.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(\s*(bid))?\s*(aux|print|load|server|logger|log|loggee|first|over|under|next|native|enter|benter|recur|precur|exit|rexit|renter|done|repeat|timeout|rear|raze|bid|start|stop|run|abort|ready)\b</string>
			<key>name</key>
			<string>keyword.control.floscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>pentity.name.function.floscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.floscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*)?(house|framer|frame)\s+(\S+)</string>
			<key>name</key>
			<string>entity.name.function.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(house|framer|frame)\b</string>
			<key>name</key>
			<string>entity.name.function.floscript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.floscript</string>
	<key>uuid</key>
	<string>0c5ea77f-252b-420d-a045-44c0ac0b851f</string>
</dict>
</plist>
